#+TITLE: Windows 上源码构建 Qt5
#+AUTHOR: Jinghui Hu
#+EMAIL: hujinghui@buaa.edu.cn
#+DATE: <2026-01-16 Fri>
#+HTML_LINK_UP: ../readme.html
#+HTML_LINK_HOME: ../index.html
#+SETUPFILE: ~/.emacs.d/site-lisp/org-html-themes/setup/theme-readtheorg-local.setup

* 系统要求
- Perl 5.8 或更高版本，安装 [[https://strawberryperl.com/][Strawberry Perl]]
- Python 2.7 或更高版本，安装 [[https://www.python.org/][Python]]
- 支持 C++11 标准的 C++ 编译器，安装 VS 2022

有关其他平台的具体要求，请参阅以下页面的 "Setting up your machine" 部分：
[[http://wiki.qt.io/Get_The_Source][http://wiki.qt.io/Get_The_Source]]

* 许可证
- 开源用户 <license> = -opensource
- 商业用户 <license> = -commercial

* Windows
打开命令提示符。确保以下工具可以在路径中找到：
- 支持的编译器（Visual Studio 2012 或更高版本， MinGW-builds gcc 4.9 或更高版本）
- Perl 5.12 或更高版本   [[http://www.activestate.com/activeperl/][http://www.activestate.com/activeperl/]]
- Python 2.7 或更高版本  [[http://www.activestate.com/activepython/][http://www.activestate.com/activepython/]]
- Ruby 1.9.3 或更高版本  [[http://rubyinstaller.org/][http://rubyinstaller.org/]]

  #+BEGIN_SRC sh
    cd qt-everywhere-src-5.15.18
    configure -prefix qtbase -opensource -nomake tests
    nmake // jom // mingw32-make
  #+END_SRC

为了加速 MSVC 下 qmake 的引导过程，可以在 configure 命令行中传递
"-make-tool jom"。如果不使用 jom，
将 "/MP" 添加到 CL 环境变量中是个不错的主意。

* 构建！
使用典型的 `configure; make` 构建过程。一些相关的 configure 选项（请参阅 configure -help）：
- -release              编译和链接 Qt 时关闭调试功能。
- -debug                编译和链接 Qt 时打开调试功能。
- -nomake tests         禁用测试构建以加快编译速度
- -nomake examples      禁用示例构建以加快编译速度
- -confirm-license      自动确认 LGPL 2.1 许可证。

** 开发者版本构建示例

#+BEGIN_SRC sh
./configure -developer-build <license>
make -j4
#+END_SRC

有关 configure 的各种选项的文档，请参阅 `./configure -help' 的输出。

上述示例将构建构建系统中默认启用的所有 Qt5 模块。

可以通过执行 `make module-<foo>' 来构建选定的模块及其依赖项。例如，仅构建 qtdeclarative 及其依赖的模块：

#+BEGIN_SRC sh
./configure -prefix $PWD/qtbase <license>
make -j4 module-qtdeclarative
#+END_SRC

如果您只对 Qt5 的一个子集感兴趣，这可以节省大量时间。

** 提示

子模块仓库 qtrepotools 包含对开发人员和发布工程师有用的脚本。考虑将 qtrepotools/bin 添加到您的 PATH 环境变量中以访问它们。

qtrepotools 中的 qt5_tool 有一些可能感兴趣的更多功能。 请尝试 `qt5_tool --help'。

* 从 git 构建 Qt5

有关更多信息，请参阅 [[http://wiki.qt.io/Building_Qt_5_from_Git][http://wiki.qt.io/Building_Qt_5_from_Git]] 和 README.git。
有关参考平台，请参阅 [[http://wiki.qt.io/Qt_5][http://wiki.qt.io/Qt_5]]。

* 文档

配置和编译 Qt 后，可以通过运行 "make docs" 来构建文档。

构建文档后，您需要使用以下命令安装它：
#+BEGIN_SRC sh
  make install_docs
#+END_SRC

文档安装在设置为 $QT_INSTALL_DOCS 的路径中。
运行 "qmake -query" 将列出 QT_INSTALL_DOCS 的值。

有关 Qt 5 文档的信息位于 qtbase/doc/README 中，或在以下页面：[[http://wiki.qt.io/Qt5DocumentationProject][http://wiki.qt.io/Qt5DocumentationProject]]

注意：文档构建仅在桌面平台上进行了测试。
