#+TITLE: Jinghui Hu's Personal Webpages
#+AUTHOR: Jinghui Hu
#+EMAIL: hujinghui@buaa.edu.cn
#+DATE: <2019-07-20 Sat 00:37:36>
#+SETUPFILE: ~/.emacs.d/site-lisp/org-html-themes/setup/theme-readtheorg-local.setup
#+TAGS: webpage home Jinghui Hu

* Study and Working
** Education Experience
- 2011/09 – 2015/07: [[https://www.buaa.edu.cn][Beihang University]], Bachelor Degree in Computer Science and
  Technology
- 2012/09 – 2015/07: [[https://www.buaa.edu.cn][Beihang University]], Second Bachelor Degree in Mathematics
  and Applied Mathematics
- 2015/09 - 2018/03: [[https://www.buaa.edu.cn][Beihang University]], Master Degree in Computer Technology
** Internship and Working Experience
- 2013/07 – 2013/09: Intern Java Programmer at [[http://www.snsoft.com.cn/index.html][Beijing City North and South
  Software Technologies Company Ltd.]]
- 2016/03 – 2016/09: Intern C# and Python Backend Programmer at [[https://www.tencent.com][Beijing City
  Tencent Computer System Company Ltd.]]
- 2017/02 - 2017/07: Intern Python Backend Programmer at [[http://www.afanti100.com][Beijing Yunjiang
  Technology Company Ltd.]]
- 2018/09 – now: Backend Programmer at [[http://www.avicmti.avic.com][AVIC Manufacturing Technology Institute]]
* Publications
- 2019
  - Hu Jinghui, Wang Xu, Ren Jian, Liu Chao (2019) Parallel Evolutionary
    Algorithm in Scheduling Work Packages to Minimize Duration of Software
    Project Management. In: Li Zheng, Jiang He, Li Ge, Zhou Minghui, Li Ming
    (eds) Software Engineering and Methodology for Emerging Domains. NASAC 2017,
    NASAC 2018. Communications in Computer and Information Science,
    vol 861. Springer, Singapore [[https://link.springer.com/chapter/10.1007/978-981-15-0310-8_3][Springer]]
- 2018
  - Jinghui Hu, Ji Wu, Han Meng, Chao Liu, and Haiyan Yang, "Signal Model of
    Automatic Testing Technology for Airborne Equipment" Computer Science,
    vol. 45, pp. 94–98, 2018. (in Chinese) [[http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2018&filename=JSJA201809016&v=MTA1MDBMejdCYjdHNEg5bk1wbzlFWW9SOGVYMUx1eFlTN0RoMVQzcVRyV00xRnJDVVJMT2ZaZVptRkNqa1VML0I=][cnki]]
  - Han Meng, Ji Wu, Jinghui Hu, Chao Liu, Haiyan Yang, and Xinyin Sun,
    "Modeling in Multiple Views and Industrial Case Study of Automatic Test for
    Hardware System" Computer Science, vol. 45, pp. 75–80, 2018. (in Chinese)
    [[http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2018&filename=JSJA201809013&v=MjMzODBGckNVUkxPZlplWm1GQ2psVnJySkx6N0JiN0c0SDluTXBvOUVaNFI4ZVgxTHV4WVM3RGgxVDNxVHJXTTE=][cnki]]
  - 吴际, 胡京徽, 崔明宝. 一种机载设备测试需求生成方法. 中国专利: CN108388231A,
    2018-08-10. [[http://dbpub.cnki.net/grid2008/dbpub/detail.aspx?dbcode=SCPD&dbname=SCPD2018&filename=CN108388231A][cnki]]
- 2017
  - 刘超, 胡京徽, 杨海燕, 吴际. 一种基于本体的 RUCM 模型一致性检查方法. 中国专
    利: CN107168762A, 2017-09-15. [[http://dbpub.cnki.net/grid2008/dbpub/detail.aspx?dbcode=SCPD&dbname=SCPD2017&filename=CN107168762A][cnki]]

* Links
1. [[https://www.linkedin.com/in/jeanhwea][LinkedIn]]
2. [[https://github.com/Jeanhwea][Github]]
3. [[file:readme.org][More details: My Blogs & Notes]]
4. [[file:links.org][Lookup]]
