#+TITLE: Makefile 笔记
#+AUTHOR: Jinghui Hu
#+EMAIL: hujinghui@buaa.edu.cn
#+DATE: <2019-08-05 Mon 20:47:16>
#+HTML_LINK_UP: ../readme.html
#+HTML_LINK_HOME: ../index.html
#+TAGS: Makefile linux commands


* Makefile
  Makefile 是 Linux 系统中的一个比较重要的工具，通常可以用来管理软件项目的编译，
  连接等作用，但是功能不仅仅如此

* 语法
** 基本语法
   Makefile 的基本语法是由目标、依赖和命令组成，它的语法如下：
   #+BEGIN_SRC makefile
     target: dependencies
         command
   #+END_SRC

   - target 执行目标，当在命令行中敲 ~make target~ 执行相应的目标
   - dependencies 依赖项，通常是一个列表，中间使用空格分隔
   - command 执行目标使用的命令，注意的是 command 的前面 *只能是 tab 符号*

** 变量
   变量定义的方法是使用一个等于号连接变量和如下：
   #+BEGIN_SRC makefile
     VAR_NAME = definition
   #+END_SRC

*** 读取文件名
    #+BEGIN_SRC makefile
      SRCS = $(shell ls *.cc)
    #+END_SRC

*** 覆盖变量
    首先在 Makefile 中定义 TEST 变量
    #+BEGIN_SRC makefile
      TEST = apple

      all:
          echo $(TEST)
    #+END_SRC

    在 make 命令后面可以使用 ~VAR=value~ 的方式可以覆盖 Makefile 里面的变量
    #+BEGIN_SRC text
      $ make all
      echo apple
      apple
      $ make all TEST=banana
      echo banana
      banana
    #+END_SRC

* 参考链接
  1. [[https://www.gnu.org/software/make/manual/make.html][GNU make]]
